### PR TITLE
Svelte 4 updates (Part 2)

### LINKED ISSUE #813: Sveltejs@4.0.0-next.0 Pre-release check
### Describe the bug

[sveltejs@4.0.0-next.0](https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0-next.0) Pre-release

- [ ] Test compatibility with sveltejs 4.0
- [x] Update `peerDependencies` by adding `|| ^4.0.0`

If you are testing 4.0.0:

```
pnpm I -D svelte@4.0.0-next.0
```

And don't forget to run this:

```
npx svelte-migrate svelte-4.
```

### PR DESCRIPTION
**Pull request by shinokada**
Closes #813

## 📑 Description

- [x] buttons/Button.svelte:81:0 A11y: <svelte:element> with click, keydown, keyup, mouseenter, mouseleave handlers must have an ARIA role
- [x] dropdowns/DropdownItem.svelte:14:2 A11y: <svelte:element> with click, keydown, keyup, mouseenter, mouseleave handlers must have an ARIA role
- [x] forms/Dropzone.svelte:14:0 A11y: Non-interactive element <label> should not be assigned mouse or keyboard event listeners.
- [x] modals/Modal.svelte:126:8 A11y: <div> with keydown handler must have an ARIA role
- [x] modals/Modal.svelte:91:2 A11y: Non-interactive element <div> should not be assigned mouse or keyboard event listeners.
- [x] navbar/NavLi.svelte:13:2 A11y: <svelte:element> with click, keydown, keypress, keyup, mouseenter, mouseleave, mouseover handlers must have an ARIA role
- [x] navbar/NavUl.svelte:25:2 A11y: <div> with click handler must have an ARIA role
- [x] paginations/PaginationItem.svelte:13:0 A11y: <svelte:element> with click, keydown, keypress, keyup, mouseenter, mouseleave, mouseover handlers must have an ARIA role
- [x] ratings/Star.svelte:10:0 A11y: <svg> with click handler must have an ARIA role
- [x] ratings/Thumbup.svelte:9:0 A11y: <svg> with click handler must have an ARIA role
- [x] ratings/Heart.svelte:9:0 A11y: <svg> with click handler must have an ARIA role
- [x] tables/TableBodyCell.svelte:12:0 A11y: Non-interactive element <td> should not be assigned mouse or keyboard event listeners.
- [x] utils/ChevronDown.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] utils/ChevronLeft.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] utils/ChevronRight.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] utils/ChevronUp.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] utils/InformationCircle.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] utils/UserCircle.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [ ] utils/Frame.svelte:84:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role
- [ ] utils/Frame.svelte:99:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role
- [x] navbar/Menu.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
- [x] carousels/Thumbnail.svelte:10:0 A11y: Non-interactive element  should not be assigned mouse or keyboard event listeners.

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

File: src/lib/buttons/Button.svelte [hunk 1]
```diff
@@ -126,7 +127,9 @@
   on:keydown
   on:keyup
   on:mouseenter
-  on:mouseleave>
+  on:mouseleave
+  role={href ? undefined : "button"}
```
Comment (jjagielka) [inline src/lib/buttons/Button.svelte]: if it is `<button>` do you need `role="button"`

Comment (shinokada) [reply src/lib/buttons/Button.svelte]: No, you don't need it if the type is a button.
I will remove that line.

**Comment by shinokada** [comment]
Since Frame is used in different components, the role will be different depending on the tag.
I just leave it for now.
