### PR TITLE
fix: #977

### LINKED ISSUE #977: Popover do not close without focus
### Describe the bug

Possible, popover has bug with `hideHandler()`. But I dont sure because dont know all cases.

### Reproduction

For example, we have popover in click-mode and complex reference element (long tree) with input field. 

After click on trigger button, popover has focus. Now we click on input field inside reference element. Occurs `focusout` event, according current condition in `hideHandler()`, popover will not close. From now, any click on any places will not close popover. We need to click on popover in order to return focus so that outside click closed him as expected.

If remove `referenceEl` from condition `focusout`, popover will close when focus lost.
```js
// hideHandler()
// now
const elements = [referenceEl, floatingEl, ...triggerEls].filter(Boolean)
// fix
const elements = [floatingEl, ...triggerEls].filter(Boolean)
```

### Flowbite version and System Info

```shell
flowbite-svelte: ^0.42.0
svelte: ^3.44.0 => 3.59.2
vite: ^2.9.13 => 2.9.16
```

### PR DESCRIPTION
**Pull request by jjagielka**
Closes #

## 📑 Description

This should fix #977

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [ ] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

File: src/lib/utils/Popper.svelte [hunk 1]
```diff
@@ -159,6 +162,10 @@
           for (const [name, handler] of events) element.removeEventListener(name, handler);
         }
       });
+      if (referenceEl) {
+        referenceEl.addEventListener('focusout', hideHandler);
```
Comment (vsergeev) [inline src/lib/utils/Popper.svelte:166]: Should these be `removeEventListener()`?

Comment (jjagielka) [reply src/lib/utils/Popper.svelte:166]: Yes it should. Thanks for a catch.
