### PR TITLE
Badge wrap

### LINKED ISSUE #621: ExampleDiv to be wrapped for badge, button-group
### Describe the bug

Some examples in the badge and button-group pages must be wrapped for small mobiles.

 
gitimg

### Reproduction

N/A

### Flowbite version and System Info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by shinokada**
Closes #621

## 📑 Description

- fix badge and button-group page
- remove SimpleSearch.svelte
- fix package.json

### CODE REVIEW

File: src/lib/buttons/Button.svelte [hunk 1]
```diff
@@ -4,11 +4,12 @@
   import type { ButtonType } from '../types';
 
   const group = getContext('group');
+  let size = getContext('size');
 
   export let pill: boolean = false;
   export let outline: boolean = false;
   export let gradient: boolean = false;
-  export let size: 'xs' | 'sm' | 'md' | 'lg' | 'xl' = group ? 'sm' : 'md';
+  // size: 'xs' | 'sm' | 'md' | 'lg' | 'xl' ='sm';
```
Comment (jjagielka) [inline src/lib/buttons/Button.svelte:12]: What have you done here?!!
Now you can't set the button size!
Check https://flowbite-svelte.com/components/button#Button_sizes

Comment (shinokada) [reply src/lib/buttons/Button.svelte:12]: oops. It's my bad.
