### PR TITLE
fix: dropzone id and event handling

### LINKED ISSUE #432: Dropzone input missing id
### Describe the bug

Currently the label is not bound to the hidden input as the input is lacking an `id`.
Further in the documentation, the example has an id passed but the Dropzone component does not have an `id` prop.

That probably was what @nthypes  meant in #414

### Reproduction

Use the `Dropzone` component in example project and try to click it. The native file picker is not opened.

### Flowbite version and System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 117.55 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.10.0 - ~/Library/Caches/fnm_multishells/40239_1668766906452/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - ~/Library/Caches/fnm_multishells/40239_1668766906452/bin/npm
    Watchman: 2022.10.10.00 - /usr/local/bin/watchman
  Browsers:
    Brave Browser: 105.1.43.93
    Firefox: 102.0.1
    Safari: 16.0
  npmPackages:
    @sveltejs/kit: 1.0.0-next.484 => 1.0.0-next.484
    svelte: ^3.44.0 => 3.52.0
    vite: ^3.1.0 => 3.1.8
```

### PR DESCRIPTION
**Pull request by oliverwebr**
Closes #432

## 📑 Description
Dropzone is broken as hidden input has not have an id. 
I added an id to the hidden input and in the second commit I added a id prop as the example page shows that Dropzone gets passed an id.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] I have updated the documentation as required (props gen)
- [x] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

**Comment by shinokada** [comment]
Thank you for your PR.

Users may use more than one dropzone. This means we can't use the same id:

```
export let id: string = 'dropzone-file';
```

This can be avoided by:

```
let id:string ='' ;
id ||= 'dropzone-file'
```

So if users don't assign the `id`, `dropzone-file` will be used. If users assign the `id`, it will use their `id`.
What do you think?

**Comment by jjagielka** [comment]
What about:
```js
import generateId from '$lib/utils/generateId';
export let id: string = generateId();
```

**Comment by oliverwebr** [comment]
> ```
> let id:string ='' ;
> id ||= 'dropzone-file'
> ```
> 
> So if users don't assign the `id`, `dropzone-file` will be used. If users assign the `id`, it will use their `id`. What do you think?

But is that not the same as my code? Users can set the id value 'dropzone-file' is just the default value. 




> What about:
> 
> ```js
> import generateId from '$lib/utils/generateId';
> export let id: string = generateId();
> ```

I think default values should be able to provide value for the lazy user. If they are generated they would be different between each build and could lead to confusion. What do you think?

**Comment by oliverwebr** [comment]
> What will happen then if you have to drop zones on the page. With the generated id no issue, with the default value you'll end up with double id.

Sure but you can set the id. But even if you have just one dropzone on your page which is part of a form you are forced to set an id because otherwise, the file will appear always under a different payload property (if send in a form etc).

File: src/lib/forms/Dropzone.svelte [hunk 1]
```diff
@@ -1,28 +1,29 @@
...
+        on:mouseleave
+        on:mouseover
+        on:dragenter
+        on:dragleave
+        on:dragover
+        on:drop>
+        <div class={innerDivClass}>
+            <slot />
+        </div>
+        <input {...$$restProps} bind:value bind:this={input} {id} type="file" class="hidden" on:change />
```
Comment (oliverwebr) [inline src/lib/forms/Dropzone.svelte]: I fixed some more issues I found while using the Dropzone. The hidden input is not able to recognize the drag events. So instead we listen on the label. Furthermore, a label/input/ div are not focusable as they are non-interactive elements / hidden. Wrapping the component in a button enables the user to `Tab` to the item. 
Controversial is that we would need to forward the click to the input. Let me know what you think.

**Comment by jjagielka** [comment]
There are lots of valuable input in that proposal. Few comments:
- you don't need to wrap the label in button: `tabIndex=0` on label will do the trick
- `input` is embedded into the `label` so attr `for` is not needed
- with the above `$$restProps` on input will solve the `id` discussion
- handling `click` is not necessary as click on label causes a click on the input
- handling of pressing Space and Enter is therefore needed as those should provoke `click` on input
- input is of type `file` so should support binding to `files` property
- I have just uploaded a trimmed down layout for drop zone
So my proposal for that PR would be:
```svelte
<script lang="ts">
  import classNames from 'classnames';

  export let value: string = '';
  export let files: FileList | undefined = undefined;
  export let defaultClass: string =
    'flex flex-col justify-center items-center w-full h-64 bg-gray-50 rounded-lg border-2 border-gray-300 border-dashed cursor-pointer dark:hover:bg-bray-800 dark:bg-gray-700 hover:bg-gray-100 dark:border-gray-600 dark:hover:border-gray-500 dark:hover:bg-gray-600';

  let input: HTMLInputElement;

  function keydown(ev: KeyboardEvent) {
    if ([' ', 'Enter'].includes(ev.key)) {
      ev.preventDefault();
      input.click();
    }
  }
</script>

<label
  class={classNames(defaultClass, $$props.class)}
  tabIndex="0"
  on:keydown={keydown}
  on:focus
  on:blur
  on:mouseenter
  on:mouseleave
  on:mouseover
  on:dragenter
  on:dragleave
  on:dragover
  on:drop>
  <slot />
  <input {...$$restProps} bind:value bind:files bind:this={input} type="file" class="hidden" on:change on:click />
</label>
```

**Comment by jjagielka** [comment]
@shinokada please approve that PR.
