### PR TITLE
fix 1214

### LINKED ISSUE #1214: Homepage container widths
### Describe the bug

The section container background should span the full width of the viewport:

Screenshot 2024-01-10 at 16 44 41

Check our website for example: https://flowbite.com/

### Reproduction

https://flowbite.com/
https://flowbite-svelte.com/

### Flowbite version and System Info

```shell
System:
    OS: macOS 14.1.2
    CPU: (12) x64 Intel(R) Core(TM) i5-10600 CPU @ 3.30GHz
    Memory: 4.60 GB / 72.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
    Yarn: 1.22.21 - ~/Downloads/flowbite-pro-marketing-ui-pages-hugo-v1.0.1/node_modules/.bin/yarn
    npm: 8.19.3 - ~/.nvm/versions/node/v18.13.0/bin/npm
    pnpm: 8.3.1 - ~/.nvm/versions/node/v18.13.0/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.1.2
  npmPackages:
    webpack: ^5.58.2 => 5.89.0
```

### PR DESCRIPTION
**Pull request by jjagielka**
Closes #1214 

## 📑 Description

- container widths corrections

## Status

- [ ] Not Completed
- [x] Completed

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] I have checked the page with https://validator.unl.edu/
- [ ] All the tests have passed
- [x] My pull request is based on the latest commit (not the npm version).

### CODE REVIEW

File: src/routes/landing/utils/Section.svelte [hunk 1]
```diff
@@ -2,8 +2,8 @@
   export let tinted: boolean = false;
 </script>
 
-<section class="{tinted ? 'bg-gray-50 dark:bg-gray-800' : ''} mx-auto max-w-8xl">
-  <div class="mx-auto px-4 lg:px-20 py-8 {$$props.class ?? ''}">
+<section class={tinted ? 'bg-gray-50 dark:bg-gray-800' : ''}>
+  <div class="mx-auto max-w-8xl px-4 lg:px-20 py-8 {$$props.class ?? ''}">
```
Comment (sanjusoftware) [inline src/routes/landing/utils/Section.svelte:6]: How can I remove / override this div class? In my case its unnecessarily adding padding on both sides and unable to take the full width available.

image
